### ISSUE TITLE
Handlebars with Phaser. Doesn't seem to want to work yet.

### ISSUE THREAD

**Issue by Wulfsbach** [christinebonk/super-ryan#23]
Not sure how to get handlebars to render phaser scenes. It is taking the css and anything within the handlebars file and ignoring anything the javascript file does although the file is linked correctly. Need to figure this one out for the game to even work as well as the start screen.

**Comment by Rye-Guy** [comment]
Yeh we'll check it out in class today. Then we can figure this thing out.
